name: Build Windows EXE

on:
  push:
    tags:
      - 'v*'   # buduje przy pushu taga w formacie vX.Y.Z
  workflow_dispatch: {}

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pillow

      - name: Build exe
        run: |
          pyinstaller --onefile --windowed -n AzulGame --icon=gui/icons/ikonka.ico --add-data "gui/icons;icons" main_window.py

      - name: Create GitHub Release (if triggered by tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifact to release (if release created)
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/AzulGame.exe
          asset_name: AzulGame.exe
          asset_content_type: application/octet-stream
          
      - name: Upload build as workflow artifact (if not release)
        if: !startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v4
        with:
          name: AzulGame-windows
          path: ./dist/AzulGame.exe
